/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.api;

import io.github.erkoristhein.mailchimp.model.PostExportsListRequest;
import io.github.erkoristhein.mailchimp.model.PostInboundAddDomain200Response;
import io.github.erkoristhein.mailchimp.model.PostInboundAddDomainRequest;
import io.github.erkoristhein.mailchimp.model.PostInboundAddRoute200Response;
import io.github.erkoristhein.mailchimp.model.PostInboundAddRouteRequest;
import io.github.erkoristhein.mailchimp.model.PostInboundCheckDomain200Response;
import io.github.erkoristhein.mailchimp.model.PostInboundCheckDomainRequest;
import io.github.erkoristhein.mailchimp.model.PostInboundDeleteDomain200Response;
import io.github.erkoristhein.mailchimp.model.PostInboundDeleteRoute200Response;
import io.github.erkoristhein.mailchimp.model.PostInboundDeleteRouteRequest;
import io.github.erkoristhein.mailchimp.model.PostInboundDomains200ResponseInner;
import io.github.erkoristhein.mailchimp.model.PostInboundRoutes200ResponseInner;
import io.github.erkoristhein.mailchimp.model.PostInboundRoutesRequest;
import io.github.erkoristhein.mailchimp.model.PostInboundSendRaw200ResponseInner;
import io.github.erkoristhein.mailchimp.model.PostInboundSendRawRequest;
import io.github.erkoristhein.mailchimp.model.PostInboundUpdateRoute200Response;
import io.github.erkoristhein.mailchimp.model.PostInboundUpdateRouteRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InboundApi
 */
@Ignore
public class InboundApiTest {

    private final InboundApi api = new InboundApi();

    
    /**
     * Add inbound domain
     *
     * Add an inbound domain to your account.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postInboundAddDomainTest() {
        PostInboundAddDomainRequest body = null;

        PostInboundAddDomain200Response response = api.postInboundAddDomain(body);

        // TODO: test validations
    }
    
    /**
     * Add mailbox route
     *
     * Add a new mailbox route to an inbound domain.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postInboundAddRouteTest() {
        PostInboundAddRouteRequest body = null;

        PostInboundAddRoute200Response response = api.postInboundAddRoute(body);

        // TODO: test validations
    }
    
    /**
     * Check domain settings
     *
     * Check the MX settings for an inbound domain. The domain must have already been added with the add-domain call.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postInboundCheckDomainTest() {
        PostInboundCheckDomainRequest body = null;

        PostInboundCheckDomain200Response response = api.postInboundCheckDomain(body);

        // TODO: test validations
    }
    
    /**
     * Delete inbound domain
     *
     * Delete an inbound domain from the account. All mail will stop routing for this domain immediately.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postInboundDeleteDomainTest() {
        PostInboundCheckDomainRequest body = null;

        PostInboundDeleteDomain200Response response = api.postInboundDeleteDomain(body);

        // TODO: test validations
    }
    
    /**
     * Delete mailbox route
     *
     * Delete an existing inbound mailbox route.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postInboundDeleteRouteTest() {
        PostInboundDeleteRouteRequest body = null;

        PostInboundDeleteRoute200Response response = api.postInboundDeleteRoute(body);

        // TODO: test validations
    }
    
    /**
     * List inbound domains
     *
     * List the domains that have been configured for inbound delivery.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postInboundDomainsTest() {
        PostExportsListRequest body = null;

        List<PostInboundDomains200ResponseInner> response = api.postInboundDomains(body);

        // TODO: test validations
    }
    
    /**
     * List mailbox routes
     *
     * List the mailbox routes defined for an inbound domain.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postInboundRoutesTest() {
        PostInboundRoutesRequest body = null;

        List<PostInboundRoutes200ResponseInner> response = api.postInboundRoutes(body);

        // TODO: test validations
    }
    
    /**
     * Send mime document
     *
     * Take a raw MIME document destined for a domain with inbound domains set up, and send it to the inbound hook exactly as if it had been sent over SMTP.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postInboundSendRawTest() {
        PostInboundSendRawRequest body = null;

        List<PostInboundSendRaw200ResponseInner> response = api.postInboundSendRaw(body);

        // TODO: test validations
    }
    
    /**
     * Update mailbox route
     *
     * Update the pattern or webhook of an existing inbound mailbox route. If null is provided for any fields, the values will remain unchanged.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postInboundUpdateRouteTest() {
        PostInboundUpdateRouteRequest body = null;

        PostInboundUpdateRoute200Response response = api.postInboundUpdateRoute(body);

        // TODO: test validations
    }
    
}
