/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.59
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.api;

import io.github.erkoristhein.mailchimp.model.PostExportsListRequest;
import io.github.erkoristhein.mailchimp.model.PostMessagesSearchTimeSeries200ResponseInner;
import io.github.erkoristhein.mailchimp.model.PostTagsDelete200Response;
import io.github.erkoristhein.mailchimp.model.PostTagsDeleteRequest;
import io.github.erkoristhein.mailchimp.model.PostTagsInfo200Response;
import io.github.erkoristhein.mailchimp.model.PostTagsInfoRequest;
import io.github.erkoristhein.mailchimp.model.PostTagsList200ResponseInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.web.client.RestClientException;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TagsApi
 */
@Disabled
class TagsApiTest {

    private final TagsApi api = new TagsApi();

    
    /**
     * View all tags history
     *
     * Return the recent history (hourly stats for the last 30 days) for all tags.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void postTagsAllTimeSeriesTest() {
        PostExportsListRequest body = null;

        List<PostMessagesSearchTimeSeries200ResponseInner> response = api.postTagsAllTimeSeries(body);

        // TODO: test validations
    }
    
    /**
     * Delete tag
     *
     * Deletes a tag permanently. Deleting a tag removes the tag from any messages that have been sent, and also deletes the tag&#39;s stats. There is no way to undo this operation, so use it carefully.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void postTagsDeleteTest() {
        PostTagsDeleteRequest body = null;

        PostTagsDelete200Response response = api.postTagsDelete(body);

        // TODO: test validations
    }
    
    /**
     * Get tag info
     *
     * Return more detailed information about a single tag, including aggregates of recent stats.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void postTagsInfoTest() {
        PostTagsInfoRequest body = null;

        PostTagsInfo200Response response = api.postTagsInfo(body);

        // TODO: test validations
    }
    
    /**
     * List tags
     *
     * Return all of the user-defined tag information.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void postTagsListTest() {
        PostExportsListRequest body = null;

        List<PostTagsList200ResponseInner> response = api.postTagsList(body);

        // TODO: test validations
    }
    
    /**
     * View tag history
     *
     * Return the recent history (hourly stats for the last 30 days) for a tag.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void postTagsTimeSeriesTest() {
        PostTagsInfoRequest body = null;

        List<PostMessagesSearchTimeSeries200ResponseInner> response = api.postTagsTimeSeries(body);

        // TODO: test validations
    }
    
}
