/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.api;

import io.github.erkoristhein.mailchimp.model.PostExportsListRequest;
import io.github.erkoristhein.mailchimp.model.PostSendersAddDomainRequest;
import io.github.erkoristhein.mailchimp.model.PostUrlsAddTrackingDomain200Response;
import io.github.erkoristhein.mailchimp.model.PostUrlsCheckTrackingDomainRequest;
import io.github.erkoristhein.mailchimp.model.PostUrlsList200ResponseInner;
import io.github.erkoristhein.mailchimp.model.PostUrlsSearchDeprecated200ResponseInner;
import io.github.erkoristhein.mailchimp.model.PostUrlsSearchDeprecatedRequest;
import io.github.erkoristhein.mailchimp.model.PostUrlsTimeSeries200ResponseInner;
import io.github.erkoristhein.mailchimp.model.PostUrlsTimeSeriesRequest;
import io.github.erkoristhein.mailchimp.model.PostUrlsTrackingDomains200ResponseInner;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UrlsApi
 */
@Ignore
public class UrlsApiTest {

    private final UrlsApi api = new UrlsApi();

    
    /**
     * Add tracking domains
     *
     * Add a tracking domain to your account.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postUrlsAddTrackingDomainTest() {
        PostSendersAddDomainRequest body = null;

        PostUrlsAddTrackingDomain200Response response = api.postUrlsAddTrackingDomain(body);

        // TODO: test validations
    }
    
    /**
     * Check cname settings
     *
     * Checks the CNAME settings for a tracking domain. The domain must have been added already with the add-tracking-domain call.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postUrlsCheckTrackingDomainTest() {
        PostUrlsCheckTrackingDomainRequest body = null;

        PostUrlsAddTrackingDomain200Response response = api.postUrlsCheckTrackingDomain(body);

        // TODO: test validations
    }
    
    /**
     * List most clicked urls
     *
     * Get the 100 most clicked URLs.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postUrlsListTest() {
        PostExportsListRequest body = null;

        List<PostUrlsList200ResponseInner> response = api.postUrlsList(body);

        // TODO: test validations
    }
    
    /**
     * Search most clicked urls
     *
     * Return the 100 most clicked URLs that match the search query given.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postUrlsSearchDeprecatedTest() {
        PostUrlsSearchDeprecatedRequest body = null;

        List<PostUrlsSearchDeprecated200ResponseInner> response = api.postUrlsSearchDeprecated(body);

        // TODO: test validations
    }
    
    /**
     * Get url history
     *
     * Return the recent history (hourly stats for the last 30 days) for a URL
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postUrlsTimeSeriesTest() {
        PostUrlsTimeSeriesRequest body = null;

        List<PostUrlsTimeSeries200ResponseInner> response = api.postUrlsTimeSeries(body);

        // TODO: test validations
    }
    
    /**
     * List tracking domains
     *
     * Get the list of tracking domains set up for this account.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postUrlsTrackingDomainsTest() {
        PostExportsListRequest body = null;

        List<PostUrlsTrackingDomains200ResponseInner> response = api.postUrlsTrackingDomains(body);

        // TODO: test validations
    }
    
}
