/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.api;

import io.github.erkoristhein.mailchimp.model.PostExportsListRequest;
import io.github.erkoristhein.mailchimp.model.PostSendersList200ResponseInner;
import io.github.erkoristhein.mailchimp.model.PostUsersInfo200Response;
import io.github.erkoristhein.mailchimp.model.PostUsersPing2200Response;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UsersApi
 */
@Ignore
public class UsersApiTest {

    private final UsersApi api = new UsersApi();

    
    /**
     * Get user info
     *
     * Return the information about the API-connected user.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postUsersInfoTest() {
        PostExportsListRequest body = null;

        PostUsersInfo200Response response = api.postUsersInfo(body);

        // TODO: test validations
    }
    
    /**
     * Ping
     *
     * Validate an API key and respond to a ping.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postUsersPingTest() {
        PostExportsListRequest body = null;

        String response = api.postUsersPing(body);

        // TODO: test validations
    }
    
    /**
     * Ping 2
     *
     * Validate an API key and respond to a ping (JSON parser version).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postUsersPing2Test() {
        PostExportsListRequest body = null;

        PostUsersPing2200Response response = api.postUsersPing2(body);

        // TODO: test validations
    }
    
    /**
     * List account senders
     *
     * Return the senders that have tried to use this account, both verified and unverified.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postUsersSendersTest() {
        PostExportsListRequest body = null;

        List<PostSendersList200ResponseInner> response = api.postUsersSenders(body);

        // TODO: test validations
    }
    
}
