/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.59
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.api;

import io.github.erkoristhein.mailchimp.model.PostAllowlistsAdd200Response;
import io.github.erkoristhein.mailchimp.model.PostAllowlistsAddRequest;
import io.github.erkoristhein.mailchimp.model.PostAllowlistsDelete200Response;
import io.github.erkoristhein.mailchimp.model.PostAllowlistsDeleteRequest;
import io.github.erkoristhein.mailchimp.model.PostAllowlistsList200ResponseInner;
import io.github.erkoristhein.mailchimp.model.PostAllowlistsListRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.web.client.RestClientException;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WhitelistsApi
 */
@Disabled
class WhitelistsApiTest {

    private final WhitelistsApi api = new WhitelistsApi();

    
    /**
     * Add email to allowlist
     *
     * Adds an email to your email rejection allowlist. If the address is currently on your denylist, that denylist entry will be removed automatically.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void postWhitelistsAddTest() {
        PostAllowlistsAddRequest body = null;

        PostAllowlistsAdd200Response response = api.postWhitelistsAdd(body);

        // TODO: test validations
    }
    
    /**
     * Remove email from allowlist
     *
     * Removes an email address from the allowlist.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void postWhitelistsDeleteTest() {
        PostAllowlistsDeleteRequest body = null;

        PostAllowlistsDelete200Response response = api.postWhitelistsDelete(body);

        // TODO: test validations
    }
    
    /**
     * List allowlisted emails
     *
     * Retrieves your email rejection allowlist. You can provide an email address or search prefix to limit the results. Returns up to 1000 results.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void postWhitelistsListTest() {
        PostAllowlistsListRequest body = null;

        List<PostAllowlistsList200ResponseInner> response = api.postWhitelistsList(body);

        // TODO: test validations
    }
    
}
