/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.59
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.model.PostMessagesContent200ResponseAttachmentsInner;
import io.github.erkoristhein.mailchimp.model.PostMessagesContent200ResponseTo;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostMessagesContent200Response
 */
class PostMessagesContent200ResponseTest {
    private final PostMessagesContent200Response model = new PostMessagesContent200Response();

    /**
     * Model tests for PostMessagesContent200Response
     */
    @Test
    void testPostMessagesContent200Response() {
        // TODO: test PostMessagesContent200Response
    }

    /**
     * Test the property 'ts'
     */
    @Test
    void tsTest() {
        // TODO: test ts
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'fromEmail'
     */
    @Test
    void fromEmailTest() {
        // TODO: test fromEmail
    }

    /**
     * Test the property 'fromName'
     */
    @Test
    void fromNameTest() {
        // TODO: test fromName
    }

    /**
     * Test the property 'subject'
     */
    @Test
    void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'to'
     */
    @Test
    void toTest() {
        // TODO: test to
    }

    /**
     * Test the property 'tags'
     */
    @Test
    void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'headers'
     */
    @Test
    void headersTest() {
        // TODO: test headers
    }

    /**
     * Test the property 'text'
     */
    @Test
    void textTest() {
        // TODO: test text
    }

    /**
     * Test the property 'html'
     */
    @Test
    void htmlTest() {
        // TODO: test html
    }

    /**
     * Test the property 'attachments'
     */
    @Test
    void attachmentsTest() {
        // TODO: test attachments
    }

}
