/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.59
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostTemplatesRender200Response
 */
class PostTemplatesRender200ResponseTest {
    private final PostTemplatesRender200Response model = new PostTemplatesRender200Response();

    /**
     * Model tests for PostTemplatesRender200Response
     */
    @Test
    void testPostTemplatesRender200Response() {
        // TODO: test PostTemplatesRender200Response
    }

    /**
     * Test the property 'html'
     */
    @Test
    void htmlTest() {
        // TODO: test html
    }

}
