/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.59
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.model.PostSendersInfo200ResponseStatsLast30Days;
import io.github.erkoristhein.mailchimp.model.PostSendersInfo200ResponseStatsLast60Days;
import io.github.erkoristhein.mailchimp.model.PostSendersInfo200ResponseStatsLast7Days;
import io.github.erkoristhein.mailchimp.model.PostSendersInfo200ResponseStatsLast90Days;
import io.github.erkoristhein.mailchimp.model.PostSendersInfo200ResponseStatsToday;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostSendersInfo200ResponseStats
 */
class PostSendersInfo200ResponseStatsTest {
    private final PostSendersInfo200ResponseStats model = new PostSendersInfo200ResponseStats();

    /**
     * Model tests for PostSendersInfo200ResponseStats
     */
    @Test
    void testPostSendersInfo200ResponseStats() {
        // TODO: test PostSendersInfo200ResponseStats
    }

    /**
     * Test the property 'today'
     */
    @Test
    void todayTest() {
        // TODO: test today
    }

    /**
     * Test the property 'last7Days'
     */
    @Test
    void last7DaysTest() {
        // TODO: test last7Days
    }

    /**
     * Test the property 'last30Days'
     */
    @Test
    void last30DaysTest() {
        // TODO: test last30Days
    }

    /**
     * Test the property 'last60Days'
     */
    @Test
    void last60DaysTest() {
        // TODO: test last60Days
    }

    /**
     * Test the property 'last90Days'
     */
    @Test
    void last90DaysTest() {
        // TODO: test last90Days
    }

}
