/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for PostUrlsSearchDeprecated200ResponseInner
 */
public class PostUrlsSearchDeprecated200ResponseInnerTest {
    private final PostUrlsSearchDeprecated200ResponseInner model = new PostUrlsSearchDeprecated200ResponseInner();

    /**
     * Model tests for PostUrlsSearchDeprecated200ResponseInner
     */
    @Test
    public void testPostUrlsSearchDeprecated200ResponseInner() {
        // TODO: test PostUrlsSearchDeprecated200ResponseInner
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'sent'
     */
    @Test
    public void sentTest() {
        // TODO: test sent
    }

    /**
     * Test the property 'clicks'
     */
    @Test
    public void clicksTest() {
        // TODO: test clicks
    }

    /**
     * Test the property 'uniqueClicks'
     */
    @Test
    public void uniqueClicksTest() {
        // TODO: test uniqueClicks
    }

}
