/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.59
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostMessagesListScheduled200ResponseInner
 */
class PostMessagesListScheduled200ResponseInnerTest {
    private final PostMessagesListScheduled200ResponseInner model = new PostMessagesListScheduled200ResponseInner();

    /**
     * Model tests for PostMessagesListScheduled200ResponseInner
     */
    @Test
    void testPostMessagesListScheduled200ResponseInner() {
        // TODO: test PostMessagesListScheduled200ResponseInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'sendAt'
     */
    @Test
    void sendAtTest() {
        // TODO: test sendAt
    }

    /**
     * Test the property 'fromEmail'
     */
    @Test
    void fromEmailTest() {
        // TODO: test fromEmail
    }

    /**
     * Test the property 'to'
     */
    @Test
    void toTest() {
        // TODO: test to
    }

    /**
     * Test the property 'subject'
     */
    @Test
    void subjectTest() {
        // TODO: test subject
    }

}
