/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for PostSendersDomains200ResponseInnerSpf
 */
public class PostSendersDomains200ResponseInnerSpfTest {
    private final PostSendersDomains200ResponseInnerSpf model = new PostSendersDomains200ResponseInnerSpf();

    /**
     * Model tests for PostSendersDomains200ResponseInnerSpf
     */
    @Test
    public void testPostSendersDomains200ResponseInnerSpf() {
        // TODO: test PostSendersDomains200ResponseInnerSpf
    }

    /**
     * Test the property 'valid'
     */
    @Test
    public void validTest() {
        // TODO: test valid
    }

    /**
     * Test the property 'validAfter'
     */
    @Test
    public void validAfterTest() {
        // TODO: test validAfter
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

}
