/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.59
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.model.PostSendersDomains200ResponseInnerDkim;
import io.github.erkoristhein.mailchimp.model.PostSendersDomains200ResponseInnerDkim2;
import io.github.erkoristhein.mailchimp.model.PostSendersDomains200ResponseInnerDmarc;
import io.github.erkoristhein.mailchimp.model.PostSendersDomains200ResponseInnerSpf;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostSendersDomains200ResponseInner
 */
class PostSendersDomains200ResponseInnerTest {
    private final PostSendersDomains200ResponseInner model = new PostSendersDomains200ResponseInner();

    /**
     * Model tests for PostSendersDomains200ResponseInner
     */
    @Test
    void testPostSendersDomains200ResponseInner() {
        // TODO: test PostSendersDomains200ResponseInner
    }

    /**
     * Test the property 'domain'
     */
    @Test
    void domainTest() {
        // TODO: test domain
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'lastTestedAt'
     */
    @Test
    void lastTestedAtTest() {
        // TODO: test lastTestedAt
    }

    /**
     * Test the property 'spf'
     */
    @Test
    void spfTest() {
        // TODO: test spf
    }

    /**
     * Test the property 'dkim'
     */
    @Test
    void dkimTest() {
        // TODO: test dkim
    }

    /**
     * Test the property 'dkim2'
     */
    @Test
    void dkim2Test() {
        // TODO: test dkim2
    }

    /**
     * Test the property 'dmarc'
     */
    @Test
    void dmarcTest() {
        // TODO: test dmarc
    }

    /**
     * Test the property 'verifiedAt'
     */
    @Test
    void verifiedAtTest() {
        // TODO: test verifiedAt
    }

    /**
     * Test the property 'validSigning'
     */
    @Test
    void validSigningTest() {
        // TODO: test validSigning
    }

    /**
     * Test the property 'verifyTxtKey'
     */
    @Test
    void verifyTxtKeyTest() {
        // TODO: test verifyTxtKey
    }

}
