/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.59
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostRejectsListRequest
 */
class PostRejectsListRequestTest {
    private final PostRejectsListRequest model = new PostRejectsListRequest();

    /**
     * Model tests for PostRejectsListRequest
     */
    @Test
    void testPostRejectsListRequest() {
        // TODO: test PostRejectsListRequest
    }

    /**
     * Test the property 'key'
     */
    @Test
    void keyTest() {
        // TODO: test key
    }

    /**
     * Test the property 'email'
     */
    @Test
    void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'includeExpired'
     */
    @Test
    void includeExpiredTest() {
        // TODO: test includeExpired
    }

    /**
     * Test the property 'subaccount'
     */
    @Test
    void subaccountTest() {
        // TODO: test subaccount
    }

}
