/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.model.PostMessagesSendRequestMessageRecipientMetadataInnerValues;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for PostMessagesSendRequestMessageRecipientMetadataInner
 */
public class PostMessagesSendRequestMessageRecipientMetadataInnerTest {
    private final PostMessagesSendRequestMessageRecipientMetadataInner model = new PostMessagesSendRequestMessageRecipientMetadataInner();

    /**
     * Model tests for PostMessagesSendRequestMessageRecipientMetadataInner
     */
    @Test
    public void testPostMessagesSendRequestMessageRecipientMetadataInner() {
        // TODO: test PostMessagesSendRequestMessageRecipientMetadataInner
    }

    /**
     * Test the property 'rcpt'
     */
    @Test
    public void rcptTest() {
        // TODO: test rcpt
    }

    /**
     * Test the property 'values'
     */
    @Test
    public void valuesTest() {
        // TODO: test values
    }

}
