/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.59
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostInboundSendRawRequest
 */
class PostInboundSendRawRequestTest {
    private final PostInboundSendRawRequest model = new PostInboundSendRawRequest();

    /**
     * Model tests for PostInboundSendRawRequest
     */
    @Test
    void testPostInboundSendRawRequest() {
        // TODO: test PostInboundSendRawRequest
    }

    /**
     * Test the property 'key'
     */
    @Test
    void keyTest() {
        // TODO: test key
    }

    /**
     * Test the property 'rawMessage'
     */
    @Test
    void rawMessageTest() {
        // TODO: test rawMessage
    }

    /**
     * Test the property 'to'
     */
    @Test
    void toTest() {
        // TODO: test to
    }

    /**
     * Test the property 'mailFrom'
     */
    @Test
    void mailFromTest() {
        // TODO: test mailFrom
    }

    /**
     * Test the property 'helo'
     */
    @Test
    void heloTest() {
        // TODO: test helo
    }

    /**
     * Test the property 'clientAddress'
     */
    @Test
    void clientAddressTest() {
        // TODO: test clientAddress
    }

}
