/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.59
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.model.PostMessagesSendRequestMessageAttachmentsInner;
import io.github.erkoristhein.mailchimp.model.PostMessagesSendRequestMessageGlobalMergeVarsInner;
import io.github.erkoristhein.mailchimp.model.PostMessagesSendRequestMessageImagesInner;
import io.github.erkoristhein.mailchimp.model.PostMessagesSendRequestMessageMergeVarsInner;
import io.github.erkoristhein.mailchimp.model.PostMessagesSendRequestMessageMetadata;
import io.github.erkoristhein.mailchimp.model.PostMessagesSendRequestMessageRecipientMetadataInner;
import io.github.erkoristhein.mailchimp.model.PostMessagesSendRequestMessageToInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostMessagesSendTemplateRequestMessage
 */
class PostMessagesSendTemplateRequestMessageTest {
    private final PostMessagesSendTemplateRequestMessage model = new PostMessagesSendTemplateRequestMessage();

    /**
     * Model tests for PostMessagesSendTemplateRequestMessage
     */
    @Test
    void testPostMessagesSendTemplateRequestMessage() {
        // TODO: test PostMessagesSendTemplateRequestMessage
    }

    /**
     * Test the property 'html'
     */
    @Test
    void htmlTest() {
        // TODO: test html
    }

    /**
     * Test the property 'text'
     */
    @Test
    void textTest() {
        // TODO: test text
    }

    /**
     * Test the property 'subject'
     */
    @Test
    void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'fromEmail'
     */
    @Test
    void fromEmailTest() {
        // TODO: test fromEmail
    }

    /**
     * Test the property 'fromName'
     */
    @Test
    void fromNameTest() {
        // TODO: test fromName
    }

    /**
     * Test the property 'to'
     */
    @Test
    void toTest() {
        // TODO: test to
    }

    /**
     * Test the property 'headers'
     */
    @Test
    void headersTest() {
        // TODO: test headers
    }

    /**
     * Test the property 'important'
     */
    @Test
    void importantTest() {
        // TODO: test important
    }

    /**
     * Test the property 'trackOpens'
     */
    @Test
    void trackOpensTest() {
        // TODO: test trackOpens
    }

    /**
     * Test the property 'trackClicks'
     */
    @Test
    void trackClicksTest() {
        // TODO: test trackClicks
    }

    /**
     * Test the property 'autoText'
     */
    @Test
    void autoTextTest() {
        // TODO: test autoText
    }

    /**
     * Test the property 'autoHtml'
     */
    @Test
    void autoHtmlTest() {
        // TODO: test autoHtml
    }

    /**
     * Test the property 'inlineCss'
     */
    @Test
    void inlineCssTest() {
        // TODO: test inlineCss
    }

    /**
     * Test the property 'urlStripQs'
     */
    @Test
    void urlStripQsTest() {
        // TODO: test urlStripQs
    }

    /**
     * Test the property 'preserveRecipients'
     */
    @Test
    void preserveRecipientsTest() {
        // TODO: test preserveRecipients
    }

    /**
     * Test the property 'viewContentLink'
     */
    @Test
    void viewContentLinkTest() {
        // TODO: test viewContentLink
    }

    /**
     * Test the property 'bccAddress'
     */
    @Test
    void bccAddressTest() {
        // TODO: test bccAddress
    }

    /**
     * Test the property 'trackingDomain'
     */
    @Test
    void trackingDomainTest() {
        // TODO: test trackingDomain
    }

    /**
     * Test the property 'signingDomain'
     */
    @Test
    void signingDomainTest() {
        // TODO: test signingDomain
    }

    /**
     * Test the property 'returnPathDomain'
     */
    @Test
    void returnPathDomainTest() {
        // TODO: test returnPathDomain
    }

    /**
     * Test the property 'merge'
     */
    @Test
    void mergeTest() {
        // TODO: test merge
    }

    /**
     * Test the property 'mergeLanguage'
     */
    @Test
    void mergeLanguageTest() {
        // TODO: test mergeLanguage
    }

    /**
     * Test the property 'globalMergeVars'
     */
    @Test
    void globalMergeVarsTest() {
        // TODO: test globalMergeVars
    }

    /**
     * Test the property 'mergeVars'
     */
    @Test
    void mergeVarsTest() {
        // TODO: test mergeVars
    }

    /**
     * Test the property 'tags'
     */
    @Test
    void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'subaccount'
     */
    @Test
    void subaccountTest() {
        // TODO: test subaccount
    }

    /**
     * Test the property 'googleAnalyticsDomains'
     */
    @Test
    void googleAnalyticsDomainsTest() {
        // TODO: test googleAnalyticsDomains
    }

    /**
     * Test the property 'googleAnalyticsCampaign'
     */
    @Test
    void googleAnalyticsCampaignTest() {
        // TODO: test googleAnalyticsCampaign
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'recipientMetadata'
     */
    @Test
    void recipientMetadataTest() {
        // TODO: test recipientMetadata
    }

    /**
     * Test the property 'attachments'
     */
    @Test
    void attachmentsTest() {
        // TODO: test attachments
    }

    /**
     * Test the property 'images'
     */
    @Test
    void imagesTest() {
        // TODO: test images
    }

}
