/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.59
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.model.PostIpsList200ResponseInnerCustomDns;
import io.github.erkoristhein.mailchimp.model.PostIpsList200ResponseInnerWarmup;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostIpsSetCustomDns200Response
 */
class PostIpsSetCustomDns200ResponseTest {
    private final PostIpsSetCustomDns200Response model = new PostIpsSetCustomDns200Response();

    /**
     * Model tests for PostIpsSetCustomDns200Response
     */
    @Test
    void testPostIpsSetCustomDns200Response() {
        // TODO: test PostIpsSetCustomDns200Response
    }

    /**
     * Test the property 'ip'
     */
    @Test
    void ipTest() {
        // TODO: test ip
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'pool'
     */
    @Test
    void poolTest() {
        // TODO: test pool
    }

    /**
     * Test the property 'domain'
     */
    @Test
    void domainTest() {
        // TODO: test domain
    }

    /**
     * Test the property 'customDns'
     */
    @Test
    void customDnsTest() {
        // TODO: test customDns
    }

    /**
     * Test the property 'warmup'
     */
    @Test
    void warmupTest() {
        // TODO: test warmup
    }

}
