/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.59
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostTemplatesTimeSeriesRequest
 */
class PostTemplatesTimeSeriesRequestTest {
    private final PostTemplatesTimeSeriesRequest model = new PostTemplatesTimeSeriesRequest();

    /**
     * Model tests for PostTemplatesTimeSeriesRequest
     */
    @Test
    void testPostTemplatesTimeSeriesRequest() {
        // TODO: test PostTemplatesTimeSeriesRequest
    }

    /**
     * Test the property 'key'
     */
    @Test
    void keyTest() {
        // TODO: test key
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

}
