/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.59
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostTagsList200ResponseInner
 */
class PostTagsList200ResponseInnerTest {
    private final PostTagsList200ResponseInner model = new PostTagsList200ResponseInner();

    /**
     * Model tests for PostTagsList200ResponseInner
     */
    @Test
    void testPostTagsList200ResponseInner() {
        // TODO: test PostTagsList200ResponseInner
    }

    /**
     * Test the property 'tag'
     */
    @Test
    void tagTest() {
        // TODO: test tag
    }

    /**
     * Test the property 'reputation'
     */
    @Test
    void reputationTest() {
        // TODO: test reputation
    }

    /**
     * Test the property 'sent'
     */
    @Test
    void sentTest() {
        // TODO: test sent
    }

    /**
     * Test the property 'hardBounces'
     */
    @Test
    void hardBouncesTest() {
        // TODO: test hardBounces
    }

    /**
     * Test the property 'softBounces'
     */
    @Test
    void softBouncesTest() {
        // TODO: test softBounces
    }

    /**
     * Test the property 'rejects'
     */
    @Test
    void rejectsTest() {
        // TODO: test rejects
    }

    /**
     * Test the property 'complaints'
     */
    @Test
    void complaintsTest() {
        // TODO: test complaints
    }

    /**
     * Test the property 'unsubs'
     */
    @Test
    void unsubsTest() {
        // TODO: test unsubs
    }

    /**
     * Test the property 'opens'
     */
    @Test
    void opensTest() {
        // TODO: test opens
    }

    /**
     * Test the property 'clicks'
     */
    @Test
    void clicksTest() {
        // TODO: test clicks
    }

    /**
     * Test the property 'uniqueOpens'
     */
    @Test
    void uniqueOpensTest() {
        // TODO: test uniqueOpens
    }

    /**
     * Test the property 'uniqueClicks'
     */
    @Test
    void uniqueClicksTest() {
        // TODO: test uniqueClicks
    }

}
