/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for PostSubaccountsUpdate200Response
 */
public class PostSubaccountsUpdate200ResponseTest {
    private final PostSubaccountsUpdate200Response model = new PostSubaccountsUpdate200Response();

    /**
     * Model tests for PostSubaccountsUpdate200Response
     */
    @Test
    public void testPostSubaccountsUpdate200Response() {
        // TODO: test PostSubaccountsUpdate200Response
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'customQuota'
     */
    @Test
    public void customQuotaTest() {
        // TODO: test customQuota
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'reputation'
     */
    @Test
    public void reputationTest() {
        // TODO: test reputation
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'firstSentAt'
     */
    @Test
    public void firstSentAtTest() {
        // TODO: test firstSentAt
    }

    /**
     * Test the property 'sentWeekly'
     */
    @Test
    public void sentWeeklyTest() {
        // TODO: test sentWeekly
    }

    /**
     * Test the property 'sentMonthly'
     */
    @Test
    public void sentMonthlyTest() {
        // TODO: test sentMonthly
    }

    /**
     * Test the property 'sentTotal'
     */
    @Test
    public void sentTotalTest() {
        // TODO: test sentTotal
    }

}
