/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.59
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.model.PostUrlsTrackingDomains200ResponseInnerCname;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostUrlsTrackingDomains200ResponseInner
 */
class PostUrlsTrackingDomains200ResponseInnerTest {
    private final PostUrlsTrackingDomains200ResponseInner model = new PostUrlsTrackingDomains200ResponseInner();

    /**
     * Model tests for PostUrlsTrackingDomains200ResponseInner
     */
    @Test
    void testPostUrlsTrackingDomains200ResponseInner() {
        // TODO: test PostUrlsTrackingDomains200ResponseInner
    }

    /**
     * Test the property 'domain'
     */
    @Test
    void domainTest() {
        // TODO: test domain
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'lastTestedAt'
     */
    @Test
    void lastTestedAtTest() {
        // TODO: test lastTestedAt
    }

    /**
     * Test the property 'cname'
     */
    @Test
    void cnameTest() {
        // TODO: test cname
    }

    /**
     * Test the property 'validTracking'
     */
    @Test
    void validTrackingTest() {
        // TODO: test validTracking
    }

}
