/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.59
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.model.PostMessagesInfo200ResponseSmtpEventsInner;
import io.github.erkoristhein.mailchimp.model.PostMessagesSearch200ResponseInnerClicksDetailInner;
import io.github.erkoristhein.mailchimp.model.PostMessagesSearch200ResponseInnerOpensDetailInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostMessagesInfo200Response
 */
class PostMessagesInfo200ResponseTest {
    private final PostMessagesInfo200Response model = new PostMessagesInfo200Response();

    /**
     * Model tests for PostMessagesInfo200Response
     */
    @Test
    void testPostMessagesInfo200Response() {
        // TODO: test PostMessagesInfo200Response
    }

    /**
     * Test the property 'ts'
     */
    @Test
    void tsTest() {
        // TODO: test ts
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'sender'
     */
    @Test
    void senderTest() {
        // TODO: test sender
    }

    /**
     * Test the property 'template'
     */
    @Test
    void templateTest() {
        // TODO: test template
    }

    /**
     * Test the property 'subject'
     */
    @Test
    void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'email'
     */
    @Test
    void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'tags'
     */
    @Test
    void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'opens'
     */
    @Test
    void opensTest() {
        // TODO: test opens
    }

    /**
     * Test the property 'opensDetail'
     */
    @Test
    void opensDetailTest() {
        // TODO: test opensDetail
    }

    /**
     * Test the property 'clicks'
     */
    @Test
    void clicksTest() {
        // TODO: test clicks
    }

    /**
     * Test the property 'clicksDetail'
     */
    @Test
    void clicksDetailTest() {
        // TODO: test clicksDetail
    }

    /**
     * Test the property 'state'
     */
    @Test
    void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'smtpEvents'
     */
    @Test
    void smtpEventsTest() {
        // TODO: test smtpEvents
    }

}
