/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.59
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostIpsProvision200Response
 */
class PostIpsProvision200ResponseTest {
    private final PostIpsProvision200Response model = new PostIpsProvision200Response();

    /**
     * Model tests for PostIpsProvision200Response
     */
    @Test
    void testPostIpsProvision200Response() {
        // TODO: test PostIpsProvision200Response
    }

    /**
     * Test the property 'requestedAt'
     */
    @Test
    void requestedAtTest() {
        // TODO: test requestedAt
    }

}
