/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.59
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * information about the dedicated IP&#39;s new configuration
 */
@JsonPropertyOrder({
  PostIpsCheckCustomDns200Response.JSON_PROPERTY_VALID,
  PostIpsCheckCustomDns200Response.JSON_PROPERTY_ERROR
})
@JsonTypeName("postIpsCheckCustomDns_200_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-26T17:07:48.465004+03:00[Europe/Helsinki]", comments = "Generator version: 7.5.0")
public class PostIpsCheckCustomDns200Response {
  public static final String JSON_PROPERTY_VALID = "valid";
  private String valid;

  public static final String JSON_PROPERTY_ERROR = "error";
  private String error;

  public PostIpsCheckCustomDns200Response() {
  }

  public PostIpsCheckCustomDns200Response valid(String valid) {
    
    this.valid = valid;
    return this;
  }

   /**
   * whether the domain name has a correctly-configured A record pointing to the ip address
   * @return valid
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValid() {
    return valid;
  }


  @JsonProperty(JSON_PROPERTY_VALID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValid(String valid) {
    this.valid = valid;
  }


  public PostIpsCheckCustomDns200Response error(String error) {
    
    this.error = error;
    return this;
  }

   /**
   * if valid is false, this will contain details about why the domain&#39;s A record is incorrect
   * @return error
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getError() {
    return error;
  }


  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setError(String error) {
    this.error = error;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostIpsCheckCustomDns200Response postIpsCheckCustomDns200Response = (PostIpsCheckCustomDns200Response) o;
    return Objects.equals(this.valid, postIpsCheckCustomDns200Response.valid) &&
        Objects.equals(this.error, postIpsCheckCustomDns200Response.error);
  }

  @Override
  public int hashCode() {
    return Objects.hash(valid, error);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostIpsCheckCustomDns200Response {\n");
    sb.append("    valid: ").append(toIndentedString(valid)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

