/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.59
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * the information on each template in the account
 */
@JsonPropertyOrder({
  PostTemplatesList200ResponseInner.JSON_PROPERTY_SLUG,
  PostTemplatesList200ResponseInner.JSON_PROPERTY_NAME,
  PostTemplatesList200ResponseInner.JSON_PROPERTY_LABELS,
  PostTemplatesList200ResponseInner.JSON_PROPERTY_CODE,
  PostTemplatesList200ResponseInner.JSON_PROPERTY_SUBJECT,
  PostTemplatesList200ResponseInner.JSON_PROPERTY_FROM_EMAIL,
  PostTemplatesList200ResponseInner.JSON_PROPERTY_FROM_NAME,
  PostTemplatesList200ResponseInner.JSON_PROPERTY_TEXT,
  PostTemplatesList200ResponseInner.JSON_PROPERTY_PUBLISH_NAME,
  PostTemplatesList200ResponseInner.JSON_PROPERTY_PUBLISH_CODE,
  PostTemplatesList200ResponseInner.JSON_PROPERTY_PUBLISH_SUBJECT,
  PostTemplatesList200ResponseInner.JSON_PROPERTY_PUBLISH_FROM_EMAIL,
  PostTemplatesList200ResponseInner.JSON_PROPERTY_PUBLISH_FROM_NAME,
  PostTemplatesList200ResponseInner.JSON_PROPERTY_PUBLISH_TEXT,
  PostTemplatesList200ResponseInner.JSON_PROPERTY_PUBLISHED_AT,
  PostTemplatesList200ResponseInner.JSON_PROPERTY_CREATED_AT,
  PostTemplatesList200ResponseInner.JSON_PROPERTY_UPDATED_AT,
  PostTemplatesList200ResponseInner.JSON_PROPERTY_IS_BROKEN_TEMPLATE
})
@JsonTypeName("postTemplatesList_200_response_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-26T17:07:48.465004+03:00[Europe/Helsinki]", comments = "Generator version: 7.5.0")
public class PostTemplatesList200ResponseInner {
  public static final String JSON_PROPERTY_SLUG = "slug";
  private String slug;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_LABELS = "labels";
  private List<String> labels = new ArrayList<>();

  public static final String JSON_PROPERTY_CODE = "code";
  private String code;

  public static final String JSON_PROPERTY_SUBJECT = "subject";
  private String subject;

  public static final String JSON_PROPERTY_FROM_EMAIL = "from_email";
  private String fromEmail;

  public static final String JSON_PROPERTY_FROM_NAME = "from_name";
  private String fromName;

  public static final String JSON_PROPERTY_TEXT = "text";
  private String text;

  public static final String JSON_PROPERTY_PUBLISH_NAME = "publish_name";
  private String publishName;

  public static final String JSON_PROPERTY_PUBLISH_CODE = "publish_code";
  private String publishCode;

  public static final String JSON_PROPERTY_PUBLISH_SUBJECT = "publish_subject";
  private String publishSubject;

  public static final String JSON_PROPERTY_PUBLISH_FROM_EMAIL = "publish_from_email";
  private String publishFromEmail;

  public static final String JSON_PROPERTY_PUBLISH_FROM_NAME = "publish_from_name";
  private String publishFromName;

  public static final String JSON_PROPERTY_PUBLISH_TEXT = "publish_text";
  private String publishText;

  public static final String JSON_PROPERTY_PUBLISHED_AT = "published_at";
  private OffsetDateTime publishedAt;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_IS_BROKEN_TEMPLATE = "is_broken_template";
  private Boolean isBrokenTemplate;

  public PostTemplatesList200ResponseInner() {
  }

  public PostTemplatesList200ResponseInner slug(String slug) {
    
    this.slug = slug;
    return this;
  }

   /**
   * the immutable unique code name of the template
   * @return slug
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SLUG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSlug() {
    return slug;
  }


  @JsonProperty(JSON_PROPERTY_SLUG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSlug(String slug) {
    this.slug = slug;
  }


  public PostTemplatesList200ResponseInner name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * the name of the template
   * @return name
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public PostTemplatesList200ResponseInner labels(List<String> labels) {
    
    this.labels = labels;
    return this;
  }

  public PostTemplatesList200ResponseInner addLabelsItem(String labelsItem) {
    if (this.labels == null) {
      this.labels = new ArrayList<>();
    }
    this.labels.add(labelsItem);
    return this;
  }

   /**
   * the list of labels applied to the template
   * @return labels
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LABELS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getLabels() {
    return labels;
  }


  @JsonProperty(JSON_PROPERTY_LABELS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLabels(List<String> labels) {
    this.labels = labels;
  }


  public PostTemplatesList200ResponseInner code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * the full HTML code of the template, with mc:edit attributes marking the editable elements - draft version
   * @return code
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCode() {
    return code;
  }


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCode(String code) {
    this.code = code;
  }


  public PostTemplatesList200ResponseInner subject(String subject) {
    
    this.subject = subject;
    return this;
  }

   /**
   * the subject line of the template, if provided - draft version
   * @return subject
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSubject() {
    return subject;
  }


  @JsonProperty(JSON_PROPERTY_SUBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubject(String subject) {
    this.subject = subject;
  }


  public PostTemplatesList200ResponseInner fromEmail(String fromEmail) {
    
    this.fromEmail = fromEmail;
    return this;
  }

   /**
   * the default sender address for the template, if provided - draft version
   * @return fromEmail
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FROM_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFromEmail() {
    return fromEmail;
  }


  @JsonProperty(JSON_PROPERTY_FROM_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFromEmail(String fromEmail) {
    this.fromEmail = fromEmail;
  }


  public PostTemplatesList200ResponseInner fromName(String fromName) {
    
    this.fromName = fromName;
    return this;
  }

   /**
   * the default sender from name for the template, if provided - draft version
   * @return fromName
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FROM_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFromName() {
    return fromName;
  }


  @JsonProperty(JSON_PROPERTY_FROM_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFromName(String fromName) {
    this.fromName = fromName;
  }


  public PostTemplatesList200ResponseInner text(String text) {
    
    this.text = text;
    return this;
  }

   /**
   * the default text part of messages sent with the template, if provided - draft version
   * @return text
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getText() {
    return text;
  }


  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setText(String text) {
    this.text = text;
  }


  public PostTemplatesList200ResponseInner publishName(String publishName) {
    
    this.publishName = publishName;
    return this;
  }

   /**
   * the same as the template name - kept as a separate field for backwards compatibility
   * @return publishName
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PUBLISH_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPublishName() {
    return publishName;
  }


  @JsonProperty(JSON_PROPERTY_PUBLISH_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPublishName(String publishName) {
    this.publishName = publishName;
  }


  public PostTemplatesList200ResponseInner publishCode(String publishCode) {
    
    this.publishCode = publishCode;
    return this;
  }

   /**
   * the full HTML code of the template, with mc:edit attributes marking the editable elements that are available as published, if it has been published
   * @return publishCode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PUBLISH_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPublishCode() {
    return publishCode;
  }


  @JsonProperty(JSON_PROPERTY_PUBLISH_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPublishCode(String publishCode) {
    this.publishCode = publishCode;
  }


  public PostTemplatesList200ResponseInner publishSubject(String publishSubject) {
    
    this.publishSubject = publishSubject;
    return this;
  }

   /**
   * the subject line of the template, if provided
   * @return publishSubject
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PUBLISH_SUBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPublishSubject() {
    return publishSubject;
  }


  @JsonProperty(JSON_PROPERTY_PUBLISH_SUBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPublishSubject(String publishSubject) {
    this.publishSubject = publishSubject;
  }


  public PostTemplatesList200ResponseInner publishFromEmail(String publishFromEmail) {
    
    this.publishFromEmail = publishFromEmail;
    return this;
  }

   /**
   * the default sender address for the template, if provided
   * @return publishFromEmail
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PUBLISH_FROM_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPublishFromEmail() {
    return publishFromEmail;
  }


  @JsonProperty(JSON_PROPERTY_PUBLISH_FROM_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPublishFromEmail(String publishFromEmail) {
    this.publishFromEmail = publishFromEmail;
  }


  public PostTemplatesList200ResponseInner publishFromName(String publishFromName) {
    
    this.publishFromName = publishFromName;
    return this;
  }

   /**
   * the default sender from name for the template, if provided
   * @return publishFromName
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PUBLISH_FROM_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPublishFromName() {
    return publishFromName;
  }


  @JsonProperty(JSON_PROPERTY_PUBLISH_FROM_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPublishFromName(String publishFromName) {
    this.publishFromName = publishFromName;
  }


  public PostTemplatesList200ResponseInner publishText(String publishText) {
    
    this.publishText = publishText;
    return this;
  }

   /**
   * the default text part of messages sent with the template, if provided
   * @return publishText
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PUBLISH_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPublishText() {
    return publishText;
  }


  @JsonProperty(JSON_PROPERTY_PUBLISH_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPublishText(String publishText) {
    this.publishText = publishText;
  }


  public PostTemplatesList200ResponseInner publishedAt(OffsetDateTime publishedAt) {
    
    this.publishedAt = publishedAt;
    return this;
  }

   /**
   * the date and time the template was last published as a UTC string in YYYY-MM-DD HH:MM:SS format, or null if it has not been published
   * @return publishedAt
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PUBLISHED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getPublishedAt() {
    return publishedAt;
  }


  @JsonProperty(JSON_PROPERTY_PUBLISHED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPublishedAt(OffsetDateTime publishedAt) {
    this.publishedAt = publishedAt;
  }


  public PostTemplatesList200ResponseInner createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * the date and time the template was first created as a UTC string in YYYY-MM-DD HH:MM:SS format
   * @return createdAt
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public PostTemplatesList200ResponseInner updatedAt(OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * the date and time the template was last modified as a UTC string in YYYY-MM-DD HH:MM:SS format
   * @return updatedAt
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public PostTemplatesList200ResponseInner isBrokenTemplate(Boolean isBrokenTemplate) {
    
    this.isBrokenTemplate = isBrokenTemplate;
    return this;
  }

   /**
   * indicates if the template is malformed or corrupt
   * @return isBrokenTemplate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_BROKEN_TEMPLATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsBrokenTemplate() {
    return isBrokenTemplate;
  }


  @JsonProperty(JSON_PROPERTY_IS_BROKEN_TEMPLATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsBrokenTemplate(Boolean isBrokenTemplate) {
    this.isBrokenTemplate = isBrokenTemplate;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostTemplatesList200ResponseInner postTemplatesList200ResponseInner = (PostTemplatesList200ResponseInner) o;
    return Objects.equals(this.slug, postTemplatesList200ResponseInner.slug) &&
        Objects.equals(this.name, postTemplatesList200ResponseInner.name) &&
        Objects.equals(this.labels, postTemplatesList200ResponseInner.labels) &&
        Objects.equals(this.code, postTemplatesList200ResponseInner.code) &&
        Objects.equals(this.subject, postTemplatesList200ResponseInner.subject) &&
        Objects.equals(this.fromEmail, postTemplatesList200ResponseInner.fromEmail) &&
        Objects.equals(this.fromName, postTemplatesList200ResponseInner.fromName) &&
        Objects.equals(this.text, postTemplatesList200ResponseInner.text) &&
        Objects.equals(this.publishName, postTemplatesList200ResponseInner.publishName) &&
        Objects.equals(this.publishCode, postTemplatesList200ResponseInner.publishCode) &&
        Objects.equals(this.publishSubject, postTemplatesList200ResponseInner.publishSubject) &&
        Objects.equals(this.publishFromEmail, postTemplatesList200ResponseInner.publishFromEmail) &&
        Objects.equals(this.publishFromName, postTemplatesList200ResponseInner.publishFromName) &&
        Objects.equals(this.publishText, postTemplatesList200ResponseInner.publishText) &&
        Objects.equals(this.publishedAt, postTemplatesList200ResponseInner.publishedAt) &&
        Objects.equals(this.createdAt, postTemplatesList200ResponseInner.createdAt) &&
        Objects.equals(this.updatedAt, postTemplatesList200ResponseInner.updatedAt) &&
        Objects.equals(this.isBrokenTemplate, postTemplatesList200ResponseInner.isBrokenTemplate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(slug, name, labels, code, subject, fromEmail, fromName, text, publishName, publishCode, publishSubject, publishFromEmail, publishFromName, publishText, publishedAt, createdAt, updatedAt, isBrokenTemplate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostTemplatesList200ResponseInner {\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    fromEmail: ").append(toIndentedString(fromEmail)).append("\n");
    sb.append("    fromName: ").append(toIndentedString(fromName)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    publishName: ").append(toIndentedString(publishName)).append("\n");
    sb.append("    publishCode: ").append(toIndentedString(publishCode)).append("\n");
    sb.append("    publishSubject: ").append(toIndentedString(publishSubject)).append("\n");
    sb.append("    publishFromEmail: ").append(toIndentedString(publishFromEmail)).append("\n");
    sb.append("    publishFromName: ").append(toIndentedString(publishFromName)).append("\n");
    sb.append("    publishText: ").append(toIndentedString(publishText)).append("\n");
    sb.append("    publishedAt: ").append(toIndentedString(publishedAt)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    isBrokenTemplate: ").append(toIndentedString(isBrokenTemplate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

