/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.59
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * the URL matching the query
 */
@JsonPropertyOrder({
  PostUrlsSearchDeprecated200ResponseInner.JSON_PROPERTY_URL,
  PostUrlsSearchDeprecated200ResponseInner.JSON_PROPERTY_SENT,
  PostUrlsSearchDeprecated200ResponseInner.JSON_PROPERTY_CLICKS,
  PostUrlsSearchDeprecated200ResponseInner.JSON_PROPERTY_UNIQUE_CLICKS
})
@JsonTypeName("postUrlsSearchDeprecated_200_response_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-26T17:07:48.465004+03:00[Europe/Helsinki]", comments = "Generator version: 7.5.0")
public class PostUrlsSearchDeprecated200ResponseInner {
  public static final String JSON_PROPERTY_URL = "url";
  private String url;

  public static final String JSON_PROPERTY_SENT = "sent";
  private Integer sent;

  public static final String JSON_PROPERTY_CLICKS = "clicks";
  private Integer clicks;

  public static final String JSON_PROPERTY_UNIQUE_CLICKS = "unique_clicks";
  private Integer uniqueClicks;

  public PostUrlsSearchDeprecated200ResponseInner() {
  }

  public PostUrlsSearchDeprecated200ResponseInner url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * the URL to be tracked
   * @return url
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(String url) {
    this.url = url;
  }


  public PostUrlsSearchDeprecated200ResponseInner sent(Integer sent) {
    
    this.sent = sent;
    return this;
  }

   /**
   * the number of emails that contained the URL
   * @return sent
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSent() {
    return sent;
  }


  @JsonProperty(JSON_PROPERTY_SENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSent(Integer sent) {
    this.sent = sent;
  }


  public PostUrlsSearchDeprecated200ResponseInner clicks(Integer clicks) {
    
    this.clicks = clicks;
    return this;
  }

   /**
   * the number of times the URL has been clicked from a tracked email
   * @return clicks
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLICKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getClicks() {
    return clicks;
  }


  @JsonProperty(JSON_PROPERTY_CLICKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClicks(Integer clicks) {
    this.clicks = clicks;
  }


  public PostUrlsSearchDeprecated200ResponseInner uniqueClicks(Integer uniqueClicks) {
    
    this.uniqueClicks = uniqueClicks;
    return this;
  }

   /**
   * the number of unique emails that have generated clicks for this URL
   * @return uniqueClicks
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UNIQUE_CLICKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getUniqueClicks() {
    return uniqueClicks;
  }


  @JsonProperty(JSON_PROPERTY_UNIQUE_CLICKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUniqueClicks(Integer uniqueClicks) {
    this.uniqueClicks = uniqueClicks;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostUrlsSearchDeprecated200ResponseInner postUrlsSearchDeprecated200ResponseInner = (PostUrlsSearchDeprecated200ResponseInner) o;
    return Objects.equals(this.url, postUrlsSearchDeprecated200ResponseInner.url) &&
        Objects.equals(this.sent, postUrlsSearchDeprecated200ResponseInner.sent) &&
        Objects.equals(this.clicks, postUrlsSearchDeprecated200ResponseInner.clicks) &&
        Objects.equals(this.uniqueClicks, postUrlsSearchDeprecated200ResponseInner.uniqueClicks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, sent, clicks, uniqueClicks);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostUrlsSearchDeprecated200ResponseInner {\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    sent: ").append(toIndentedString(sent)).append("\n");
    sb.append("    clicks: ").append(toIndentedString(clicks)).append("\n");
    sb.append("    uniqueClicks: ").append(toIndentedString(uniqueClicks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

