/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.59
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.model.PostUsersInfo200ResponseStatsAllTime;
import io.github.erkoristhein.mailchimp.model.PostUsersInfo200ResponseStatsLast30Days;
import io.github.erkoristhein.mailchimp.model.PostUsersInfo200ResponseStatsLast60Days;
import io.github.erkoristhein.mailchimp.model.PostUsersInfo200ResponseStatsLast7Days;
import io.github.erkoristhein.mailchimp.model.PostUsersInfo200ResponseStatsLast90Days;
import io.github.erkoristhein.mailchimp.model.PostUsersInfo200ResponseStatsToday;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * an aggregate summary of the account&#39;s sending stats
 */
@JsonPropertyOrder({
  PostUsersInfo200ResponseStats.JSON_PROPERTY_TODAY,
  PostUsersInfo200ResponseStats.JSON_PROPERTY_LAST7_DAYS,
  PostUsersInfo200ResponseStats.JSON_PROPERTY_LAST30_DAYS,
  PostUsersInfo200ResponseStats.JSON_PROPERTY_LAST60_DAYS,
  PostUsersInfo200ResponseStats.JSON_PROPERTY_LAST90_DAYS,
  PostUsersInfo200ResponseStats.JSON_PROPERTY_ALL_TIME
})
@JsonTypeName("postUsersInfo_200_response_stats")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-26T17:07:48.465004+03:00[Europe/Helsinki]", comments = "Generator version: 7.5.0")
public class PostUsersInfo200ResponseStats {
  public static final String JSON_PROPERTY_TODAY = "today";
  private PostUsersInfo200ResponseStatsToday today;

  public static final String JSON_PROPERTY_LAST7_DAYS = "last_7_days";
  private PostUsersInfo200ResponseStatsLast7Days last7Days;

  public static final String JSON_PROPERTY_LAST30_DAYS = "last_30_days";
  private PostUsersInfo200ResponseStatsLast30Days last30Days;

  public static final String JSON_PROPERTY_LAST60_DAYS = "last_60_days";
  private PostUsersInfo200ResponseStatsLast60Days last60Days;

  public static final String JSON_PROPERTY_LAST90_DAYS = "last_90_days";
  private PostUsersInfo200ResponseStatsLast90Days last90Days;

  public static final String JSON_PROPERTY_ALL_TIME = "all_time";
  private PostUsersInfo200ResponseStatsAllTime allTime;

  public PostUsersInfo200ResponseStats() {
  }

  public PostUsersInfo200ResponseStats today(PostUsersInfo200ResponseStatsToday today) {
    
    this.today = today;
    return this;
  }

   /**
   * Get today
   * @return today
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TODAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PostUsersInfo200ResponseStatsToday getToday() {
    return today;
  }


  @JsonProperty(JSON_PROPERTY_TODAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToday(PostUsersInfo200ResponseStatsToday today) {
    this.today = today;
  }


  public PostUsersInfo200ResponseStats last7Days(PostUsersInfo200ResponseStatsLast7Days last7Days) {
    
    this.last7Days = last7Days;
    return this;
  }

   /**
   * Get last7Days
   * @return last7Days
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST7_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PostUsersInfo200ResponseStatsLast7Days getLast7Days() {
    return last7Days;
  }


  @JsonProperty(JSON_PROPERTY_LAST7_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLast7Days(PostUsersInfo200ResponseStatsLast7Days last7Days) {
    this.last7Days = last7Days;
  }


  public PostUsersInfo200ResponseStats last30Days(PostUsersInfo200ResponseStatsLast30Days last30Days) {
    
    this.last30Days = last30Days;
    return this;
  }

   /**
   * Get last30Days
   * @return last30Days
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST30_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PostUsersInfo200ResponseStatsLast30Days getLast30Days() {
    return last30Days;
  }


  @JsonProperty(JSON_PROPERTY_LAST30_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLast30Days(PostUsersInfo200ResponseStatsLast30Days last30Days) {
    this.last30Days = last30Days;
  }


  public PostUsersInfo200ResponseStats last60Days(PostUsersInfo200ResponseStatsLast60Days last60Days) {
    
    this.last60Days = last60Days;
    return this;
  }

   /**
   * Get last60Days
   * @return last60Days
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST60_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PostUsersInfo200ResponseStatsLast60Days getLast60Days() {
    return last60Days;
  }


  @JsonProperty(JSON_PROPERTY_LAST60_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLast60Days(PostUsersInfo200ResponseStatsLast60Days last60Days) {
    this.last60Days = last60Days;
  }


  public PostUsersInfo200ResponseStats last90Days(PostUsersInfo200ResponseStatsLast90Days last90Days) {
    
    this.last90Days = last90Days;
    return this;
  }

   /**
   * Get last90Days
   * @return last90Days
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST90_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PostUsersInfo200ResponseStatsLast90Days getLast90Days() {
    return last90Days;
  }


  @JsonProperty(JSON_PROPERTY_LAST90_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLast90Days(PostUsersInfo200ResponseStatsLast90Days last90Days) {
    this.last90Days = last90Days;
  }


  public PostUsersInfo200ResponseStats allTime(PostUsersInfo200ResponseStatsAllTime allTime) {
    
    this.allTime = allTime;
    return this;
  }

   /**
   * Get allTime
   * @return allTime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ALL_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PostUsersInfo200ResponseStatsAllTime getAllTime() {
    return allTime;
  }


  @JsonProperty(JSON_PROPERTY_ALL_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAllTime(PostUsersInfo200ResponseStatsAllTime allTime) {
    this.allTime = allTime;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostUsersInfo200ResponseStats postUsersInfo200ResponseStats = (PostUsersInfo200ResponseStats) o;
    return Objects.equals(this.today, postUsersInfo200ResponseStats.today) &&
        Objects.equals(this.last7Days, postUsersInfo200ResponseStats.last7Days) &&
        Objects.equals(this.last30Days, postUsersInfo200ResponseStats.last30Days) &&
        Objects.equals(this.last60Days, postUsersInfo200ResponseStats.last60Days) &&
        Objects.equals(this.last90Days, postUsersInfo200ResponseStats.last90Days) &&
        Objects.equals(this.allTime, postUsersInfo200ResponseStats.allTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(today, last7Days, last30Days, last60Days, last90Days, allTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostUsersInfo200ResponseStats {\n");
    sb.append("    today: ").append(toIndentedString(today)).append("\n");
    sb.append("    last7Days: ").append(toIndentedString(last7Days)).append("\n");
    sb.append("    last30Days: ").append(toIndentedString(last30Days)).append("\n");
    sb.append("    last60Days: ").append(toIndentedString(last60Days)).append("\n");
    sb.append("    last90Days: ").append(toIndentedString(last90Days)).append("\n");
    sb.append("    allTime: ").append(toIndentedString(allTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

