/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.59
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * information about the status of the pool that was deleted
 */
@JsonPropertyOrder({
  PostIpsDeletePool200Response.JSON_PROPERTY_POOL,
  PostIpsDeletePool200Response.JSON_PROPERTY_DELETED
})
@JsonTypeName("postIpsDeletePool_200_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-26T17:07:48.465004+03:00[Europe/Helsinki]", comments = "Generator version: 7.5.0")
public class PostIpsDeletePool200Response {
  public static final String JSON_PROPERTY_POOL = "pool";
  private String pool;

  public static final String JSON_PROPERTY_DELETED = "deleted";
  private Boolean deleted;

  public PostIpsDeletePool200Response() {
  }

  public PostIpsDeletePool200Response pool(String pool) {
    
    this.pool = pool;
    return this;
  }

   /**
   * the name of the pool
   * @return pool
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPool() {
    return pool;
  }


  @JsonProperty(JSON_PROPERTY_POOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPool(String pool) {
    this.pool = pool;
  }


  public PostIpsDeletePool200Response deleted(Boolean deleted) {
    
    this.deleted = deleted;
    return this;
  }

   /**
   * whether the pool was deleted
   * @return deleted
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDeleted() {
    return deleted;
  }


  @JsonProperty(JSON_PROPERTY_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostIpsDeletePool200Response postIpsDeletePool200Response = (PostIpsDeletePool200Response) o;
    return Objects.equals(this.pool, postIpsDeletePool200Response.pool) &&
        Objects.equals(this.deleted, postIpsDeletePool200Response.deleted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pool, deleted);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostIpsDeletePool200Response {\n");
    sb.append("    pool: ").append(toIndentedString(pool)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

