/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.59
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * the individual webhook info
 */
@JsonPropertyOrder({
  PostWebhooksList200ResponseInner.JSON_PROPERTY_ID,
  PostWebhooksList200ResponseInner.JSON_PROPERTY_URL,
  PostWebhooksList200ResponseInner.JSON_PROPERTY_DESCRIPTION,
  PostWebhooksList200ResponseInner.JSON_PROPERTY_AUTH_KEY,
  PostWebhooksList200ResponseInner.JSON_PROPERTY_EVENTS,
  PostWebhooksList200ResponseInner.JSON_PROPERTY_CREATED_AT,
  PostWebhooksList200ResponseInner.JSON_PROPERTY_LAST_SENT_AT,
  PostWebhooksList200ResponseInner.JSON_PROPERTY_BATCHES_SENT,
  PostWebhooksList200ResponseInner.JSON_PROPERTY_EVENTS_SENT,
  PostWebhooksList200ResponseInner.JSON_PROPERTY_LAST_ERROR
})
@JsonTypeName("postWebhooksList_200_response_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-26T17:07:48.465004+03:00[Europe/Helsinki]", comments = "Generator version: 7.5.0")
public class PostWebhooksList200ResponseInner {
  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_URL = "url";
  private String url;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_AUTH_KEY = "auth_key";
  private String authKey;

  /**
   * the individual message event
   */
  public enum EventsEnum {
    SEND("send"),
    
    HARD_BOUNCE("hard_bounce"),
    
    SOFT_BOUNCE("soft_bounce"),
    
    OPEN("open"),
    
    CLICK("click"),
    
    SPAM("spam"),
    
    UNSUB("unsub"),
    
    REJECT("reject");

    private String value;

    EventsEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static EventsEnum fromValue(String value) {
      for (EventsEnum b : EventsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_EVENTS = "events";
  private List<EventsEnum> events = new ArrayList<>();

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_LAST_SENT_AT = "last_sent_at";
  private OffsetDateTime lastSentAt;

  public static final String JSON_PROPERTY_BATCHES_SENT = "batches_sent";
  private Integer batchesSent;

  public static final String JSON_PROPERTY_EVENTS_SENT = "events_sent";
  private Integer eventsSent;

  public static final String JSON_PROPERTY_LAST_ERROR = "last_error";
  private String lastError;

  public PostWebhooksList200ResponseInner() {
  }

  public PostWebhooksList200ResponseInner id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * a unique integer indentifier for the webhook
   * @return id
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Integer id) {
    this.id = id;
  }


  public PostWebhooksList200ResponseInner url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * The URL that the event data will be posted to
   * @return url
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(String url) {
    this.url = url;
  }


  public PostWebhooksList200ResponseInner description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * a description of the webhook
   * @return description
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public PostWebhooksList200ResponseInner authKey(String authKey) {
    
    this.authKey = authKey;
    return this;
  }

   /**
   * the key used to requests for this webhook
   * @return authKey
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUTH_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAuthKey() {
    return authKey;
  }


  @JsonProperty(JSON_PROPERTY_AUTH_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthKey(String authKey) {
    this.authKey = authKey;
  }


  public PostWebhooksList200ResponseInner events(List<EventsEnum> events) {
    
    this.events = events;
    return this;
  }

  public PostWebhooksList200ResponseInner addEventsItem(EventsEnum eventsItem) {
    if (this.events == null) {
      this.events = new ArrayList<>();
    }
    this.events.add(eventsItem);
    return this;
  }

   /**
   * The message events that will be posted to the hook
   * @return events
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<EventsEnum> getEvents() {
    return events;
  }


  @JsonProperty(JSON_PROPERTY_EVENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEvents(List<EventsEnum> events) {
    this.events = events;
  }


  public PostWebhooksList200ResponseInner createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * the date and time that the webhook was created as a UTC string in YYYY-MM-DD HH:MM:SS format
   * @return createdAt
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public PostWebhooksList200ResponseInner lastSentAt(OffsetDateTime lastSentAt) {
    
    this.lastSentAt = lastSentAt;
    return this;
  }

   /**
   * the date and time that the webhook last successfully received events as a UTC string in YYYY-MM-DD HH:MM:SS format
   * @return lastSentAt
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_SENT_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getLastSentAt() {
    return lastSentAt;
  }


  @JsonProperty(JSON_PROPERTY_LAST_SENT_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastSentAt(OffsetDateTime lastSentAt) {
    this.lastSentAt = lastSentAt;
  }


  public PostWebhooksList200ResponseInner batchesSent(Integer batchesSent) {
    
    this.batchesSent = batchesSent;
    return this;
  }

   /**
   * the number of event batches that have ever been sent to this webhook
   * @return batchesSent
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BATCHES_SENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getBatchesSent() {
    return batchesSent;
  }


  @JsonProperty(JSON_PROPERTY_BATCHES_SENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBatchesSent(Integer batchesSent) {
    this.batchesSent = batchesSent;
  }


  public PostWebhooksList200ResponseInner eventsSent(Integer eventsSent) {
    
    this.eventsSent = eventsSent;
    return this;
  }

   /**
   * the total number of events that have ever been sent to this webhook
   * @return eventsSent
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVENTS_SENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getEventsSent() {
    return eventsSent;
  }


  @JsonProperty(JSON_PROPERTY_EVENTS_SENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventsSent(Integer eventsSent) {
    this.eventsSent = eventsSent;
  }


  public PostWebhooksList200ResponseInner lastError(String lastError) {
    
    this.lastError = lastError;
    return this;
  }

   /**
   * if we&#39;ve ever gotten an error trying to post to this webhook, the last error that we&#39;ve seen
   * @return lastError
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLastError() {
    return lastError;
  }


  @JsonProperty(JSON_PROPERTY_LAST_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastError(String lastError) {
    this.lastError = lastError;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostWebhooksList200ResponseInner postWebhooksList200ResponseInner = (PostWebhooksList200ResponseInner) o;
    return Objects.equals(this.id, postWebhooksList200ResponseInner.id) &&
        Objects.equals(this.url, postWebhooksList200ResponseInner.url) &&
        Objects.equals(this.description, postWebhooksList200ResponseInner.description) &&
        Objects.equals(this.authKey, postWebhooksList200ResponseInner.authKey) &&
        Objects.equals(this.events, postWebhooksList200ResponseInner.events) &&
        Objects.equals(this.createdAt, postWebhooksList200ResponseInner.createdAt) &&
        Objects.equals(this.lastSentAt, postWebhooksList200ResponseInner.lastSentAt) &&
        Objects.equals(this.batchesSent, postWebhooksList200ResponseInner.batchesSent) &&
        Objects.equals(this.eventsSent, postWebhooksList200ResponseInner.eventsSent) &&
        Objects.equals(this.lastError, postWebhooksList200ResponseInner.lastError);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, url, description, authKey, events, createdAt, lastSentAt, batchesSent, eventsSent, lastError);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostWebhooksList200ResponseInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    authKey: ").append(toIndentedString(authKey)).append("\n");
    sb.append("    events: ").append(toIndentedString(events)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    lastSentAt: ").append(toIndentedString(lastSentAt)).append("\n");
    sb.append("    batchesSent: ").append(toIndentedString(batchesSent)).append("\n");
    sb.append("    eventsSent: ").append(toIndentedString(eventsSent)).append("\n");
    sb.append("    lastError: ").append(toIndentedString(lastError)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

