/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * information about the domain
 */
@JsonPropertyOrder({
  PostInboundAddDomain200Response.JSON_PROPERTY_DOMAIN,
  PostInboundAddDomain200Response.JSON_PROPERTY_CREATED_AT,
  PostInboundAddDomain200Response.JSON_PROPERTY_VALID_MX
})
@JsonTypeName("postInboundAddDomain_200_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-19T14:58:48.420021+02:00[Europe/Tallinn]")
public class PostInboundAddDomain200Response {
  public static final String JSON_PROPERTY_DOMAIN = "domain";
  private String domain;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_VALID_MX = "valid_mx";
  private Boolean validMx;

  public PostInboundAddDomain200Response() {
  }

  public PostInboundAddDomain200Response domain(String domain) {
    
    this.domain = domain;
    return this;
  }

   /**
   * the domain name that is accepting mail
   * @return domain
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOMAIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDomain() {
    return domain;
  }


  @JsonProperty(JSON_PROPERTY_DOMAIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDomain(String domain) {
    this.domain = domain;
  }


  public PostInboundAddDomain200Response createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * the date and time that the inbound domain was added as a UTC string in YYYY-MM-DD HH:MM:SS format
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public PostInboundAddDomain200Response validMx(Boolean validMx) {
    
    this.validMx = validMx;
    return this;
  }

   /**
   * true if this inbound domain has successfully set up an MX record to deliver mail to the Mandrill servers
   * @return validMx
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALID_MX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getValidMx() {
    return validMx;
  }


  @JsonProperty(JSON_PROPERTY_VALID_MX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidMx(Boolean validMx) {
    this.validMx = validMx;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostInboundAddDomain200Response postInboundAddDomain200Response = (PostInboundAddDomain200Response) o;
    return Objects.equals(this.domain, postInboundAddDomain200Response.domain) &&
        Objects.equals(this.createdAt, postInboundAddDomain200Response.createdAt) &&
        Objects.equals(this.validMx, postInboundAddDomain200Response.validMx);
  }

  @Override
  public int hashCode() {
    return Objects.hash(domain, createdAt, validMx);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostInboundAddDomain200Response {\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    validMx: ").append(toIndentedString(validMx)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

