/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.59
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * the individual export info
 */
@JsonPropertyOrder({
  PostExportsList200ResponseInner.JSON_PROPERTY_ID,
  PostExportsList200ResponseInner.JSON_PROPERTY_CREATED_AT,
  PostExportsList200ResponseInner.JSON_PROPERTY_TYPE,
  PostExportsList200ResponseInner.JSON_PROPERTY_FINISHED_AT,
  PostExportsList200ResponseInner.JSON_PROPERTY_STATE,
  PostExportsList200ResponseInner.JSON_PROPERTY_RESULT_URL
})
@JsonTypeName("postExportsList_200_response_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-26T17:07:48.465004+03:00[Europe/Helsinki]", comments = "Generator version: 7.5.0")
public class PostExportsList200ResponseInner {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;

  public static final String JSON_PROPERTY_FINISHED_AT = "finished_at";
  private OffsetDateTime finishedAt;

  public static final String JSON_PROPERTY_STATE = "state";
  private String state;

  public static final String JSON_PROPERTY_RESULT_URL = "result_url";
  private String resultUrl;

  public PostExportsList200ResponseInner() {
  }

  public PostExportsList200ResponseInner id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * the unique identifier for this Export. Use this identifier when checking the export job&#39;s status
   * @return id
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public PostExportsList200ResponseInner createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * the date and time that the export job was created as a UTC string in YYYY-MM-DD HH:MM:SS format
   * @return createdAt
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public PostExportsList200ResponseInner type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * the type of the export job - activity, reject, or allowlist
   * @return type
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(String type) {
    this.type = type;
  }


  public PostExportsList200ResponseInner finishedAt(OffsetDateTime finishedAt) {
    
    this.finishedAt = finishedAt;
    return this;
  }

   /**
   * the date and time that the export job was finished as a UTC string in YYYY-MM-DD HH:MM:SS format
   * @return finishedAt
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FINISHED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getFinishedAt() {
    return finishedAt;
  }


  @JsonProperty(JSON_PROPERTY_FINISHED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFinishedAt(OffsetDateTime finishedAt) {
    this.finishedAt = finishedAt;
  }


  public PostExportsList200ResponseInner state(String state) {
    
    this.state = state;
    return this;
  }

   /**
   * the export job&#39;s state - waiting, working, complete, error, or expired.
   * @return state
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(String state) {
    this.state = state;
  }


  public PostExportsList200ResponseInner resultUrl(String resultUrl) {
    
    this.resultUrl = resultUrl;
    return this;
  }

   /**
   * the url for the export job&#39;s results, if the job is completed.
   * @return resultUrl
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESULT_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getResultUrl() {
    return resultUrl;
  }


  @JsonProperty(JSON_PROPERTY_RESULT_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResultUrl(String resultUrl) {
    this.resultUrl = resultUrl;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostExportsList200ResponseInner postExportsList200ResponseInner = (PostExportsList200ResponseInner) o;
    return Objects.equals(this.id, postExportsList200ResponseInner.id) &&
        Objects.equals(this.createdAt, postExportsList200ResponseInner.createdAt) &&
        Objects.equals(this.type, postExportsList200ResponseInner.type) &&
        Objects.equals(this.finishedAt, postExportsList200ResponseInner.finishedAt) &&
        Objects.equals(this.state, postExportsList200ResponseInner.state) &&
        Objects.equals(this.resultUrl, postExportsList200ResponseInner.resultUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createdAt, type, finishedAt, state, resultUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostExportsList200ResponseInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    finishedAt: ").append(toIndentedString(finishedAt)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    resultUrl: ").append(toIndentedString(resultUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

