/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.model.PostUrlsTrackingDomains200ResponseInnerCname;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * information about the tracking domain
 */
@JsonPropertyOrder({
  PostUrlsAddTrackingDomain200Response.JSON_PROPERTY_DOMAIN,
  PostUrlsAddTrackingDomain200Response.JSON_PROPERTY_CREATED_AT,
  PostUrlsAddTrackingDomain200Response.JSON_PROPERTY_LAST_TESTED_AT,
  PostUrlsAddTrackingDomain200Response.JSON_PROPERTY_CNAME,
  PostUrlsAddTrackingDomain200Response.JSON_PROPERTY_VALID_TRACKING
})
@JsonTypeName("postUrlsAddTrackingDomain_200_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-19T14:58:48.420021+02:00[Europe/Tallinn]")
public class PostUrlsAddTrackingDomain200Response {
  public static final String JSON_PROPERTY_DOMAIN = "domain";
  private String domain;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_LAST_TESTED_AT = "last_tested_at";
  private OffsetDateTime lastTestedAt;

  public static final String JSON_PROPERTY_CNAME = "cname";
  private PostUrlsTrackingDomains200ResponseInnerCname cname;

  public static final String JSON_PROPERTY_VALID_TRACKING = "valid_tracking";
  private Boolean validTracking;

  public PostUrlsAddTrackingDomain200Response() {
  }

  public PostUrlsAddTrackingDomain200Response domain(String domain) {
    
    this.domain = domain;
    return this;
  }

   /**
   * the tracking domain name
   * @return domain
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOMAIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDomain() {
    return domain;
  }


  @JsonProperty(JSON_PROPERTY_DOMAIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDomain(String domain) {
    this.domain = domain;
  }


  public PostUrlsAddTrackingDomain200Response createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * the date and time that the tracking domain was added as a UTC string in YYYY-MM-DD HH:MM:SS format
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public PostUrlsAddTrackingDomain200Response lastTestedAt(OffsetDateTime lastTestedAt) {
    
    this.lastTestedAt = lastTestedAt;
    return this;
  }

   /**
   * when the domain&#39;s DNS settings were last tested as a UTC string in YYYY-MM-DD HH:MM:SS format
   * @return lastTestedAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_TESTED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getLastTestedAt() {
    return lastTestedAt;
  }


  @JsonProperty(JSON_PROPERTY_LAST_TESTED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastTestedAt(OffsetDateTime lastTestedAt) {
    this.lastTestedAt = lastTestedAt;
  }


  public PostUrlsAddTrackingDomain200Response cname(PostUrlsTrackingDomains200ResponseInnerCname cname) {
    
    this.cname = cname;
    return this;
  }

   /**
   * Get cname
   * @return cname
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PostUrlsTrackingDomains200ResponseInnerCname getCname() {
    return cname;
  }


  @JsonProperty(JSON_PROPERTY_CNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCname(PostUrlsTrackingDomains200ResponseInnerCname cname) {
    this.cname = cname;
  }


  public PostUrlsAddTrackingDomain200Response validTracking(Boolean validTracking) {
    
    this.validTracking = validTracking;
    return this;
  }

   /**
   * whether this domain can be used as a tracking domain for email.
   * @return validTracking
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALID_TRACKING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getValidTracking() {
    return validTracking;
  }


  @JsonProperty(JSON_PROPERTY_VALID_TRACKING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidTracking(Boolean validTracking) {
    this.validTracking = validTracking;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostUrlsAddTrackingDomain200Response postUrlsAddTrackingDomain200Response = (PostUrlsAddTrackingDomain200Response) o;
    return Objects.equals(this.domain, postUrlsAddTrackingDomain200Response.domain) &&
        Objects.equals(this.createdAt, postUrlsAddTrackingDomain200Response.createdAt) &&
        Objects.equals(this.lastTestedAt, postUrlsAddTrackingDomain200Response.lastTestedAt) &&
        Objects.equals(this.cname, postUrlsAddTrackingDomain200Response.cname) &&
        Objects.equals(this.validTracking, postUrlsAddTrackingDomain200Response.validTracking);
  }

  @Override
  public int hashCode() {
    return Objects.hash(domain, createdAt, lastTestedAt, cname, validTracking);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostUrlsAddTrackingDomain200Response {\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    lastTestedAt: ").append(toIndentedString(lastTestedAt)).append("\n");
    sb.append("    cname: ").append(toIndentedString(cname)).append("\n");
    sb.append("    validTracking: ").append(toIndentedString(validTracking)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

