/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PostIpsSetPoolRequest
 */
@JsonPropertyOrder({
  PostIpsSetPoolRequest.JSON_PROPERTY_KEY,
  PostIpsSetPoolRequest.JSON_PROPERTY_IP,
  PostIpsSetPoolRequest.JSON_PROPERTY_POOL,
  PostIpsSetPoolRequest.JSON_PROPERTY_CREATE_POOL
})
@JsonTypeName("postIpsSetPool_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-19T14:58:48.420021+02:00[Europe/Tallinn]")
public class PostIpsSetPoolRequest {
  public static final String JSON_PROPERTY_KEY = "key";
  private String key;

  public static final String JSON_PROPERTY_IP = "ip";
  private String ip;

  public static final String JSON_PROPERTY_POOL = "pool";
  private String pool;

  public static final String JSON_PROPERTY_CREATE_POOL = "create_pool";
  private Boolean createPool;

  public PostIpsSetPoolRequest() {
  }

  public PostIpsSetPoolRequest key(String key) {
    
    this.key = key;
    return this;
  }

   /**
   * a valid api key
   * @return key
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getKey() {
    return key;
  }


  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKey(String key) {
    this.key = key;
  }


  public PostIpsSetPoolRequest ip(String ip) {
    
    this.ip = ip;
    return this;
  }

   /**
   * a dedicated ip address
   * @return ip
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getIp() {
    return ip;
  }


  @JsonProperty(JSON_PROPERTY_IP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIp(String ip) {
    this.ip = ip;
  }


  public PostIpsSetPoolRequest pool(String pool) {
    
    this.pool = pool;
    return this;
  }

   /**
   * the name of the new pool to add the dedicated ip to
   * @return pool
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_POOL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPool() {
    return pool;
  }


  @JsonProperty(JSON_PROPERTY_POOL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPool(String pool) {
    this.pool = pool;
  }


  public PostIpsSetPoolRequest createPool(Boolean createPool) {
    
    this.createPool = createPool;
    return this;
  }

   /**
   * whether to create the pool if it does not exist; if false and the pool does not exist, an Unknown_Pool will be thrown.
   * @return createPool
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATE_POOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCreatePool() {
    return createPool;
  }


  @JsonProperty(JSON_PROPERTY_CREATE_POOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatePool(Boolean createPool) {
    this.createPool = createPool;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostIpsSetPoolRequest postIpsSetPoolRequest = (PostIpsSetPoolRequest) o;
    return Objects.equals(this.key, postIpsSetPoolRequest.key) &&
        Objects.equals(this.ip, postIpsSetPoolRequest.ip) &&
        Objects.equals(this.pool, postIpsSetPoolRequest.pool) &&
        Objects.equals(this.createPool, postIpsSetPoolRequest.createPool);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, ip, pool, createPool);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostIpsSetPoolRequest {\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    ip: ").append(toIndentedString(ip)).append("\n");
    sb.append("    pool: ").append(toIndentedString(pool)).append("\n");
    sb.append("    createPool: ").append(toIndentedString(createPool)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

