/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.model.PostTagsInfo200ResponseStatsLast30Days;
import io.github.erkoristhein.mailchimp.model.PostTagsInfo200ResponseStatsLast60Days;
import io.github.erkoristhein.mailchimp.model.PostTagsInfo200ResponseStatsLast7Days;
import io.github.erkoristhein.mailchimp.model.PostTagsInfo200ResponseStatsLast90Days;
import io.github.erkoristhein.mailchimp.model.PostTagsInfo200ResponseStatsToday;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * an aggregate summary of the tag&#39;s sending stats
 */
@JsonPropertyOrder({
  PostTagsInfo200ResponseStats.JSON_PROPERTY_TODAY,
  PostTagsInfo200ResponseStats.JSON_PROPERTY_LAST7_DAYS,
  PostTagsInfo200ResponseStats.JSON_PROPERTY_LAST30_DAYS,
  PostTagsInfo200ResponseStats.JSON_PROPERTY_LAST60_DAYS,
  PostTagsInfo200ResponseStats.JSON_PROPERTY_LAST90_DAYS
})
@JsonTypeName("postTagsInfo_200_response_stats")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-19T14:58:48.420021+02:00[Europe/Tallinn]")
public class PostTagsInfo200ResponseStats {
  public static final String JSON_PROPERTY_TODAY = "today";
  private PostTagsInfo200ResponseStatsToday today;

  public static final String JSON_PROPERTY_LAST7_DAYS = "last_7_days";
  private PostTagsInfo200ResponseStatsLast7Days last7Days;

  public static final String JSON_PROPERTY_LAST30_DAYS = "last_30_days";
  private PostTagsInfo200ResponseStatsLast30Days last30Days;

  public static final String JSON_PROPERTY_LAST60_DAYS = "last_60_days";
  private PostTagsInfo200ResponseStatsLast60Days last60Days;

  public static final String JSON_PROPERTY_LAST90_DAYS = "last_90_days";
  private PostTagsInfo200ResponseStatsLast90Days last90Days;

  public PostTagsInfo200ResponseStats() {
  }

  public PostTagsInfo200ResponseStats today(PostTagsInfo200ResponseStatsToday today) {
    
    this.today = today;
    return this;
  }

   /**
   * Get today
   * @return today
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TODAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PostTagsInfo200ResponseStatsToday getToday() {
    return today;
  }


  @JsonProperty(JSON_PROPERTY_TODAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToday(PostTagsInfo200ResponseStatsToday today) {
    this.today = today;
  }


  public PostTagsInfo200ResponseStats last7Days(PostTagsInfo200ResponseStatsLast7Days last7Days) {
    
    this.last7Days = last7Days;
    return this;
  }

   /**
   * Get last7Days
   * @return last7Days
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST7_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PostTagsInfo200ResponseStatsLast7Days getLast7Days() {
    return last7Days;
  }


  @JsonProperty(JSON_PROPERTY_LAST7_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLast7Days(PostTagsInfo200ResponseStatsLast7Days last7Days) {
    this.last7Days = last7Days;
  }


  public PostTagsInfo200ResponseStats last30Days(PostTagsInfo200ResponseStatsLast30Days last30Days) {
    
    this.last30Days = last30Days;
    return this;
  }

   /**
   * Get last30Days
   * @return last30Days
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST30_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PostTagsInfo200ResponseStatsLast30Days getLast30Days() {
    return last30Days;
  }


  @JsonProperty(JSON_PROPERTY_LAST30_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLast30Days(PostTagsInfo200ResponseStatsLast30Days last30Days) {
    this.last30Days = last30Days;
  }


  public PostTagsInfo200ResponseStats last60Days(PostTagsInfo200ResponseStatsLast60Days last60Days) {
    
    this.last60Days = last60Days;
    return this;
  }

   /**
   * Get last60Days
   * @return last60Days
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST60_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PostTagsInfo200ResponseStatsLast60Days getLast60Days() {
    return last60Days;
  }


  @JsonProperty(JSON_PROPERTY_LAST60_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLast60Days(PostTagsInfo200ResponseStatsLast60Days last60Days) {
    this.last60Days = last60Days;
  }


  public PostTagsInfo200ResponseStats last90Days(PostTagsInfo200ResponseStatsLast90Days last90Days) {
    
    this.last90Days = last90Days;
    return this;
  }

   /**
   * Get last90Days
   * @return last90Days
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST90_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PostTagsInfo200ResponseStatsLast90Days getLast90Days() {
    return last90Days;
  }


  @JsonProperty(JSON_PROPERTY_LAST90_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLast90Days(PostTagsInfo200ResponseStatsLast90Days last90Days) {
    this.last90Days = last90Days;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostTagsInfo200ResponseStats postTagsInfo200ResponseStats = (PostTagsInfo200ResponseStats) o;
    return Objects.equals(this.today, postTagsInfo200ResponseStats.today) &&
        Objects.equals(this.last7Days, postTagsInfo200ResponseStats.last7Days) &&
        Objects.equals(this.last30Days, postTagsInfo200ResponseStats.last30Days) &&
        Objects.equals(this.last60Days, postTagsInfo200ResponseStats.last60Days) &&
        Objects.equals(this.last90Days, postTagsInfo200ResponseStats.last90Days);
  }

  @Override
  public int hashCode() {
    return Objects.hash(today, last7Days, last30Days, last60Days, last90Days);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostTagsInfo200ResponseStats {\n");
    sb.append("    today: ").append(toIndentedString(today)).append("\n");
    sb.append("    last7Days: ").append(toIndentedString(last7Days)).append("\n");
    sb.append("    last30Days: ").append(toIndentedString(last30Days)).append("\n");
    sb.append("    last60Days: ").append(toIndentedString(last60Days)).append("\n");
    sb.append("    last90Days: ").append(toIndentedString(last90Days)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

