/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.59
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * a description of the provisioning request that was created
 */
@JsonPropertyOrder({
  PostIpsProvision200Response.JSON_PROPERTY_REQUESTED_AT
})
@JsonTypeName("postIpsProvision_200_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-26T17:07:48.465004+03:00[Europe/Helsinki]", comments = "Generator version: 7.5.0")
public class PostIpsProvision200Response {
  public static final String JSON_PROPERTY_REQUESTED_AT = "requested_at";
  private OffsetDateTime requestedAt;

  public PostIpsProvision200Response() {
  }

  public PostIpsProvision200Response requestedAt(OffsetDateTime requestedAt) {
    
    this.requestedAt = requestedAt;
    return this;
  }

   /**
   * the date and time that the request was created as a UTC timestamp in YYYY-MM-DD HH:MM:SS format
   * @return requestedAt
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REQUESTED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getRequestedAt() {
    return requestedAt;
  }


  @JsonProperty(JSON_PROPERTY_REQUESTED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequestedAt(OffsetDateTime requestedAt) {
    this.requestedAt = requestedAt;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostIpsProvision200Response postIpsProvision200Response = (PostIpsProvision200Response) o;
    return Objects.equals(this.requestedAt, postIpsProvision200Response.requestedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostIpsProvision200Response {\n");
    sb.append("    requestedAt: ").append(toIndentedString(requestedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

