/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * information on an individual open
 */
@JsonPropertyOrder({
  PostMessagesSearch200ResponseInnerOpensDetailInner.JSON_PROPERTY_TS,
  PostMessagesSearch200ResponseInnerOpensDetailInner.JSON_PROPERTY_IP,
  PostMessagesSearch200ResponseInnerOpensDetailInner.JSON_PROPERTY_LOCATION,
  PostMessagesSearch200ResponseInnerOpensDetailInner.JSON_PROPERTY_UA
})
@JsonTypeName("postMessagesSearch_200_response_inner_opens_detail_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-19T14:58:48.420021+02:00[Europe/Tallinn]")
public class PostMessagesSearch200ResponseInnerOpensDetailInner {
  public static final String JSON_PROPERTY_TS = "ts";
  private Integer ts;

  public static final String JSON_PROPERTY_IP = "ip";
  private String ip;

  public static final String JSON_PROPERTY_LOCATION = "location";
  private String location;

  public static final String JSON_PROPERTY_UA = "ua";
  private String ua;

  public PostMessagesSearch200ResponseInnerOpensDetailInner() {
  }

  public PostMessagesSearch200ResponseInnerOpensDetailInner ts(Integer ts) {
    
    this.ts = ts;
    return this;
  }

   /**
   * the unix timestamp from when the message was opened
   * @return ts
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTs() {
    return ts;
  }


  @JsonProperty(JSON_PROPERTY_TS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTs(Integer ts) {
    this.ts = ts;
  }


  public PostMessagesSearch200ResponseInnerOpensDetailInner ip(String ip) {
    
    this.ip = ip;
    return this;
  }

   /**
   * the IP address that generated the open
   * @return ip
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIp() {
    return ip;
  }


  @JsonProperty(JSON_PROPERTY_IP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIp(String ip) {
    this.ip = ip;
  }


  public PostMessagesSearch200ResponseInnerOpensDetailInner location(String location) {
    
    this.location = location;
    return this;
  }

   /**
   * the approximate region and country that the opening IP is located
   * @return location
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocation() {
    return location;
  }


  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocation(String location) {
    this.location = location;
  }


  public PostMessagesSearch200ResponseInnerOpensDetailInner ua(String ua) {
    
    this.ua = ua;
    return this;
  }

   /**
   * the email client or browser data of the open
   * @return ua
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUa() {
    return ua;
  }


  @JsonProperty(JSON_PROPERTY_UA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUa(String ua) {
    this.ua = ua;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostMessagesSearch200ResponseInnerOpensDetailInner postMessagesSearch200ResponseInnerOpensDetailInner = (PostMessagesSearch200ResponseInnerOpensDetailInner) o;
    return Objects.equals(this.ts, postMessagesSearch200ResponseInnerOpensDetailInner.ts) &&
        Objects.equals(this.ip, postMessagesSearch200ResponseInnerOpensDetailInner.ip) &&
        Objects.equals(this.location, postMessagesSearch200ResponseInnerOpensDetailInner.location) &&
        Objects.equals(this.ua, postMessagesSearch200ResponseInnerOpensDetailInner.ua);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ts, ip, location, ua);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostMessagesSearch200ResponseInnerOpensDetailInner {\n");
    sb.append("    ts: ").append(toIndentedString(ts)).append("\n");
    sb.append("    ip: ").append(toIndentedString(ip)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    ua: ").append(toIndentedString(ua)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

