/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.59
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * the individual domain info
 */
@JsonPropertyOrder({
  PostInboundDomains200ResponseInner.JSON_PROPERTY_DOMAIN,
  PostInboundDomains200ResponseInner.JSON_PROPERTY_CREATED_AT,
  PostInboundDomains200ResponseInner.JSON_PROPERTY_VALID_MX
})
@JsonTypeName("postInboundDomains_200_response_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-26T17:07:48.465004+03:00[Europe/Helsinki]", comments = "Generator version: 7.5.0")
public class PostInboundDomains200ResponseInner {
  public static final String JSON_PROPERTY_DOMAIN = "domain";
  private String domain;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_VALID_MX = "valid_mx";
  private Boolean validMx;

  public PostInboundDomains200ResponseInner() {
  }

  public PostInboundDomains200ResponseInner domain(String domain) {
    
    this.domain = domain;
    return this;
  }

   /**
   * the domain name that is accepting mail
   * @return domain
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOMAIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDomain() {
    return domain;
  }


  @JsonProperty(JSON_PROPERTY_DOMAIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDomain(String domain) {
    this.domain = domain;
  }


  public PostInboundDomains200ResponseInner createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * the date and time that the inbound domain was added as a UTC string in YYYY-MM-DD HH:MM:SS format
   * @return createdAt
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public PostInboundDomains200ResponseInner validMx(Boolean validMx) {
    
    this.validMx = validMx;
    return this;
  }

   /**
   * true if this inbound domain has successfully set up an MX record to deliver mail to the Mandrill servers
   * @return validMx
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALID_MX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getValidMx() {
    return validMx;
  }


  @JsonProperty(JSON_PROPERTY_VALID_MX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidMx(Boolean validMx) {
    this.validMx = validMx;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostInboundDomains200ResponseInner postInboundDomains200ResponseInner = (PostInboundDomains200ResponseInner) o;
    return Objects.equals(this.domain, postInboundDomains200ResponseInner.domain) &&
        Objects.equals(this.createdAt, postInboundDomains200ResponseInner.createdAt) &&
        Objects.equals(this.validMx, postInboundDomains200ResponseInner.validMx);
  }

  @Override
  public int hashCode() {
    return Objects.hash(domain, createdAt, validMx);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostInboundDomains200ResponseInner {\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    validMx: ").append(toIndentedString(validMx)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

