/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PostInboundAddRouteRequest
 */
@JsonPropertyOrder({
  PostInboundAddRouteRequest.JSON_PROPERTY_KEY,
  PostInboundAddRouteRequest.JSON_PROPERTY_DOMAIN,
  PostInboundAddRouteRequest.JSON_PROPERTY_PATTERN,
  PostInboundAddRouteRequest.JSON_PROPERTY_URL
})
@JsonTypeName("postInboundAddRoute_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-19T14:58:48.420021+02:00[Europe/Tallinn]")
public class PostInboundAddRouteRequest {
  public static final String JSON_PROPERTY_KEY = "key";
  private String key;

  public static final String JSON_PROPERTY_DOMAIN = "domain";
  private String domain;

  public static final String JSON_PROPERTY_PATTERN = "pattern";
  private String pattern;

  public static final String JSON_PROPERTY_URL = "url";
  private String url;

  public PostInboundAddRouteRequest() {
  }

  public PostInboundAddRouteRequest key(String key) {
    
    this.key = key;
    return this;
  }

   /**
   * a valid api key
   * @return key
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getKey() {
    return key;
  }


  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKey(String key) {
    this.key = key;
  }


  public PostInboundAddRouteRequest domain(String domain) {
    
    this.domain = domain;
    return this;
  }

   /**
   * an existing inbound domain
   * @return domain
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DOMAIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDomain() {
    return domain;
  }


  @JsonProperty(JSON_PROPERTY_DOMAIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDomain(String domain) {
    this.domain = domain;
  }


  public PostInboundAddRouteRequest pattern(String pattern) {
    
    this.pattern = pattern;
    return this;
  }

   /**
   * the search pattern that the mailbox name should match
   * @return pattern
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PATTERN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPattern() {
    return pattern;
  }


  @JsonProperty(JSON_PROPERTY_PATTERN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPattern(String pattern) {
    this.pattern = pattern;
  }


  public PostInboundAddRouteRequest url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * the webhook URL where the inbound messages will be published
   * @return url
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUrl(String url) {
    this.url = url;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostInboundAddRouteRequest postInboundAddRouteRequest = (PostInboundAddRouteRequest) o;
    return Objects.equals(this.key, postInboundAddRouteRequest.key) &&
        Objects.equals(this.domain, postInboundAddRouteRequest.domain) &&
        Objects.equals(this.pattern, postInboundAddRouteRequest.pattern) &&
        Objects.equals(this.url, postInboundAddRouteRequest.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, domain, pattern, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostInboundAddRouteRequest {\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    pattern: ").append(toIndentedString(pattern)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

