/*
 * Mailchimp Transactional API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.59
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * a struct with one key \&quot;PING\&quot; with a static value \&quot;PONG!\&quot;
 */
@JsonPropertyOrder({
  PostUsersPing2200Response.JSON_PROPERTY_P_I_N_G
})
@JsonTypeName("postUsersPing2_200_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-26T17:07:48.465004+03:00[Europe/Helsinki]", comments = "Generator version: 7.5.0")
public class PostUsersPing2200Response {
  public static final String JSON_PROPERTY_P_I_N_G = "PING";
  private String PING;

  public PostUsersPing2200Response() {
  }

  public PostUsersPing2200Response PING(String PING) {
    
    this.PING = PING;
    return this;
  }

   /**
   * a simple pong response
   * @return PING
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_P_I_N_G)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPING() {
    return PING;
  }


  @JsonProperty(JSON_PROPERTY_P_I_N_G)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPING(String PING) {
    this.PING = PING;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostUsersPing2200Response postUsersPing2200Response = (PostUsersPing2200Response) o;
    return Objects.equals(this.PING, postUsersPing2200Response.PING);
  }

  @Override
  public int hashCode() {
    return Objects.hash(PING);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostUsersPing2200Response {\n");
    sb.append("    PING: ").append(toIndentedString(PING)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

